FROM node:15-alpine AS builder

WORKDIR /app

COPY package.json package.json

RUN npm install

COPY . .

ARG REACT_APP_CONTRACTADDR
ENV REACT_APP_CONTRACTADDR=$REACT_APP_CONTRACTADDR

ARG REACT_APP_EXPLORER
ENV REACT_APP_EXPLORER=$REACT_APP_EXPLORER

ARG REACT_APP_INFURA_IPFS_SECRET
ENV REACT_APP_CONTRACTADDR=$REACT_APP_INFURA_IPFS_SECRET

ARG REACT_APP_INFURA_IPFS_PROJECTID
ENV REACT_APP_INFURA_IPFS_PROJECTID=$REACT_APP_INFURA_IPFS_PROJECTID

RUN npm run build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf *

COPY --from=builder /app/dist .

CMD ["npm", "run", "start"]
